name: CI using action

on:
  push:
    branches:
      - main

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t myusername/myapp:${{ github.sha }} .

      # Step 4: Push Docker image
      - name: Push Docker image
        run: |
          docker push myusername/myapp:${{ github.sha }}
